### ISSUE TITLE
Do you have the model?

### ISSUE THREAD

**Issue by zilpe** [ConstantinoSchillebeeckx/cherry-mx-switch#1]
Hello. If possible, please could I get a download for the model? It's not inside the file

**Comment by ConstantinoSchillebeeckxSimpleRose** [comment]
Yep, use the [step file](https://github.com/ConstantinoSchillebeeckx/cherry-mx-switch/blob/master/switch.step) in the root directory.

**Comment by ArshZilpe** [comment]
Thank you. I didn’t see that before.
